export const location = [
  {
    id: "KR-11",
    title: ["Seoul", "서울", "seoul", "SEOUL", "서울특별시", "서울시"],
    nx: 60,
    ny: 127,
  },
  {
    id: "KR-41",
    title: ["Gyeonggi", "경기", "gyeonggi", "GYEONGGI", "경기도"],
    nx: 60,
    ny: 120,
  },
  {
    id: "KR-28",
    title: ["Incheon", "인천", "incheon", "INCHEON", "인천광역시", "인천시"],
    nx: 55,
    ny: 124,
  },
  {
    id: "KR-42",
    title: ["Gangwon", "강원", "gangwon", "GANGWON", "강원도"],
    nx: 73,
    ny: 134,
  },
  {
    id: "KR-48",
    title: [
      "Gyeongsangnam-do",
      "경상남도",
      "경남",
      "gyeongsangnam-do",
      "GYEONGSANGNAM-DO",
    ],
    nx: 91,
    ny: 77,
  },
  {
    id: "KR-47",
    title: [
      "Gyeongsangbuk-do",
      "경상북도",
      "경북",
      "gyeongsangbuk-do",
      "GYEONGSANGBUK-DO",
    ],
    nx: 87,
    ny: 106,
  },
  {
    id: "KR-46",
    title: ["Jeollanam-do", "전라남도", "전남", "jeollanam-do", "JEOLLANAM-DO"],
    nx: 51,
    ny: 67,
  },
  {
    id: "KR-45",
    title: ["Jeollabuk-do", "전라북도", "전북", "jeollabuk-do", "JEOLLABUK-DO"],
    nx: 63,
    ny: 89,
  },
  {
    id: "KR-44",
    title: [
      "Chungcheongnam-do",
      "충청남도",
      "충남",
      "chungcheongnam-do",
      "CHUNGCHEONGNAM-DO",
    ],
    nx: 68,
    ny: 100,
  },
  {
    id: "KR-43",
    title: [
      "Chungcheongbuk-do",
      "충청북도",
      "충북",
      "chungcheongbuk-do",
      "CHUNGCHEONGBUK-DO",
    ],
    nx: 69,
    ny: 107,
  },
  {
    id: "KR-50",
    title: ["Sejong", "세종", "세종시", "세종특별자치시", "sejong", "SEJONG"],
    nx: 66,
    ny: 103,
  },
  {
    id: "KR-30",
    title: ["Daejeon", "대전", "대전광역시", "대전시", "daejeon", "DAEJEON"],
    nx: 67,
    ny: 100,
  },
  {
    id: "KR-27",
    title: ["Daegu", "대구", "대구시", "대구광역시", "daegu", "DAEGU"],
    nx: 89,
    ny: 90,
  },
  {
    id: "KR-26",
    title: ["Busan", "부산", "부산시", "부산광역시", "busan", "BUSAN"],
    nx: 98,
    ny: 76,
  },
  {
    id: "KR-31",
    title: ["Ulsan", "울산", "울산시", "울산광역시", "ulsan", "ULSAN"],
    nx: 102,
    ny: 84,
  },
  {
    id: "KR-29",
    title: ["Gwangju", "광주", "광주시", "광주광역시", "gwangju", "GWANGJU"],
    nx: 58,
    ny: 74,
  },
  {
    id: "KR-49",
    title: ["Jeju", "제주", "제주도", "제주특별자치도", "jeju", "JEJU"],
    nx: 52,
    ny: 38,
  },
];
